[package]
name = "ssbcol"
version = "0.2.3"
authors = ["tehzz"]

[dependencies]
clap = "2.25.0"
error-chain = "0.11.0"
byteorder = "1.1.0"
bitflags = "0.9.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
